# Generated by Django 3.1 on 2020-08-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='home_city',
            field=models.CharField(blank=True, default='What City Are You From?', max_length=100),
        ),
    ]
