# Generated by Django 3.1 on 2020-08-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200806_1653'),
        ('main_app', '0006_auto_20200806_0521'),
    ]

    operations = [
    ]
