# Generated by Django 3.1 on 2020-08-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200806_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='img_url',
        ),
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(default='default_city.jpg', upload_to='city_pics/'),
        ),
    ]
